Python: Use FloatImage::New() instead of nullptr in thin
The default argument `nullptr` wasn't converted by pybind11 to FloatImage::Pointer
Because this failure converting to FloatImage::Pointer, `sgext.scripts.thin`
required to always provide a distance map image, or an error of type
will arise:

```
TypeError: thin(): incompatible function arguments. The following argument types are supported:
    1. (input: itk::SmartPointer<itk::Image<unsigned char,3> >,
    skel_type: str, select_type: str, tables_folder: str, persistence: int = 0,
    input_distance_map_image: itk::SmartPointer<itk::Image<float,3> > = None,
    profile: bool = False, verbose: bool = False, visualize: bool = False) -> itk::SmartPointer<itk::Image<unsigned char,3> >
```

To solve it, I had to change the order the pybind11 modules are
compiled, `itk` is needed before `scripts`.

Reported by @NeuZhangQiang in VTK:
https://discourse.vtk.org/t/vmtk-center-lines-extraction-how-to-accelerate-it-and-how-to-extract-center-lines-from-small-vessel/4103/10