CMake: Fix using TBB in Linux
error: Even when TBB not found, the target TBB::tbb exist.
solution: Check for TBB_FOUND before using the target.

error:
```bash
-- TBB_FOUND: 0. tbb_libraries: TBB::tbb
CMake Error in /home/vsts/work/1/s/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "TBB::tbb" includes non-existent path

    "TBB_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```