COMP: Fix template instantiation itk::ImportImageFilter
Dimension is zero?
Only in Windows, and only in azure-pipelines

```
FAILED: wrap/CMakeFiles/_sgext.dir/itk/itk_image_py.cpp.obj
D:\a\1\build_deps\ITK-src\Modules\Core\Common\include\itkImportImageFilter.h(128):
error C2676: binary '[': 'itk::Point<itk::ImageBase<0>::PointValueType,0>'
does not define this operator or a conversion to a type acceptable to the predefined operator
D:\a\1\build_deps\ITK-src\Modules\Core\Common\include\itkImportImageFilter.h(128):
note: while compiling class template member function 'void
itk::ImportImageFilter<PixelType,0>::SetOrigin(const float [])'
D:\a\1\s\wrap\itk\declare_itk_image_py.h(91): note: see reference to
class template instantiation 'itk::ImportImageFilter<PixelType,0>' being
compiled
```